import { LOCATION_FIELD_CODES_ENUM } from './location-field-codes.const'


export const CONSTRUCTION_CODE = [
    'UNSUNS',
    'WOOFRA',
    'MASUNS',
    'MASUNR',
    'MASREI',
    'MASCON',
    'MASADO',
    'CONUNS',
    'CONRPR',
    'CONRCF',
    'CONRCS',
    'CONRTU',
    'STLUNS',
    'STLFRA',
    'STLLMF',
    'MOBUNS',
    'MOBWTD',
    'MOBNTD',
    'GLAGRE',
];

export const CONSTRUCTION_CLASS = [
  'Wood frames' ,
  'Unreinforced masonry' ,
  'Reinforced masonry' ,
  'Confined masonry' ,
  'Adobe' ,
  'Reinforced concrete precast' ,
  'Reinforced concrete cast-in-place frame' ,
  'Reinforced concrete cast-in-place shear wall' ,
  'Reinforced concrete tilt-up' ,
  'Steel frames' ,
  'Light metal frames' ,
  'With tie-downs' ,
  'Without tie-downs' ,
  'Greenhouses',
  'Unspecified'
];

export const OCCUPANCY_SCHEME = [
   'RMS',
   'ACCORD',
   'AIR'
];

export const OCCUPANCY_CODE = [
    'AGRCUL001' ,
    'AGRCUL002' ,
    'AGRCUL003' ,
    'AGRCUL004' ,
    'AGRCUL005' ,
    'AGRCUL006' ,
    'AGRCUL007' ,
    'AGRCUL999' ,
    'AGRGEN999' ,
    'AGRINF001' ,
    'AGRINF002' ,
    'AGRINF999' ,
    'COMADM001' ,
    'COMADM002' ,
    'COMADM003' ,
    'COMADM004' ,
    'COMADM005' ,
    'COMADM006' ,
    'COMADM007' ,
    'COMADM008' ,
    'COMADM009' ,
    'COMADM010' ,
    'COMADM011' ,
    'COMADM999' ,
    'COMGEN999' ,
    'COMLRG999' ,
    'COMPUB001' ,
    'COMPUB002' ,
    'COMPUB003' ,
    'COMPUB004' ,
    'COMPUB005' ,
    'COMPUB006' ,
    'COMPUB007' ,
    'COMPUB008' ,
    'COMPUB009' ,
    'COMPUB010' ,
    'COMPUB011' ,
    'COMPUB012' ,
    'COMPUB013' ,
    'COMPUB999' ,
    'COMRTL001' ,
    'COMRTL002' ,
    'COMRTL003' ,
    'COMRTL004' ,
    'COMRTL005' ,
    'COMRTL006' ,
    'COMRTL007' ,
    'COMRTL008' ,
    'COMRTL009' ,
    'COMRTL010' ,
    'COMRTL011' ,
    'COMRTL012' ,
    'COMRTL013' ,
    'COMRTL999' ,
    'COMSML999' ,
  '  INCE999' ,
    'INDCHM001' ,
    'INDCHM002' ,
    'INDCHM003' ,
    'INDCHM004' ,
    'INDCHM005' ,
    'INDCHM006' ,
    'INDCHM007' ,
    'INDCHM008' ,
    'INDCHM009' ,
    'INDCHM010' ,
    'INDCHM011' ,
    'INDCHM012' ,
    'INDCHM013' ,
    'INDCHM014' ,
    'INDCHM015' ,
    'INDCHM016' ,
    'INDCHM017' ,
    'INDCHM018' ,
    'INDCHM019' ,
    'INDCHM020' ,
    'INDCHM021' ,
    'INDCHM022' ,
    'INDCHM023' ,
    'INDCHM999' ,
    'INDELE001' ,
    'INDELE002' ,
    'INDELE003' ,
    'INDELE004' ,
    'INDELE005' ,
    'INDELE006' ,
    'INDELE007' ,
    'INDELE008' ,
    'INDELE009' ,
    'INDELE010' ,
    'INDELE011' ,
    'INDELE999' ,
    'INDELE999' ,
    'INDFBT001' ,
    'INDFBT002' ,
    'INDFBT003' ,
    'INDFBT004' ,
    'INDFBT005' ,
    'INDFBT006' ,
    'INDFBT007' ,
    'INDFBT008' ,
    'INDFBT009' ,
    'INDFBT010' ,
    'INDFBT011' ,
    'INDFBT012' ,
    'INDFBT013' ,
    'INDFBT014' ,
    'INDFBT015' ,
    'INDFBT015' ,
    'INDFBT016' ,
    'INDFBT017' ,
    'INDFBT018' ,
    'INDFBT019' ,
    'INDFBT020' ,
    'INDFBT021' ,
    'INDFBT999' ,
    'INDGEN999' ,
    'INDHVY999' ,
    'INDLIT999' ,
    'INDMAC001' ,
    'INDMAC002' ,
    'INDMAC003' ,
    'INDMAC004' ,
    'INDMAC005' ,
    'INDMAC006' ,
    'INDMAC007' ,
    'INDMAC008' ,
    'INDMAC009' ,
    'INDMAC010' ,
    'INDMAC011' ,
    'INDMAC012' ,
    'INDMAC999' ,
    'INDMIN001' ,
    'INDMIN002' ,
    'INDMIN003' ,
    'INDMIN003' ,
    'INDMIN003' ,
    'INDMIN004' ,
    'INDMIN004' ,
    'INDMIN005' ,
    'INDMIN006' ,
    'INDMIN007' ,
    'INDMIN008' ,
    'INDMIN008' ,
    'INDMIN009' ,
    'INDMIN010' ,
    'INDMIN010' ,
    'INDMIN010' ,
    'INDMIN011' ,
    'INDMIN011' ,
    'INDMIN012' ,
    'INDMIN013' ,
    'INDMIN014' ,
    'INDMIN015' ,
    'INDMIN016' ,
    'INDMIN017' ,
    'INDMIN018' ,
    'INDMIN019' ,
    'INDMIN020' ,
    'INDMIN020' ,
    'INDMIN021' ,
    'INDMIN022' ,
    'INDMIN022' ,
    'INDMIN999' ,
    'INDNMM001' ,
    'INDNMM002' ,
    'INDNMM003' ,
    'INDNMM004' ,
    'INDNMM005' ,
    'INDNMM006' ,
    'INDNMM007' ,
    'INDNMM008' ,
    'INDNMM009' ,
    'INDNMM010' ,
    'INDNMM011' ,
    'INDNMM012' ,
    'INDNMM013' ,
    'INDNMM014' ,
    'INDNMM015' ,
    'INDNMM016' ,
    'INDNMM017' ,
    'INDNMM018' ,
    'INDNMM019' ,
    'INDNMM020' ,
    'INDNMM021' ,
    'INDNMM999' ,
    'INDOOF001' ,
    'INDOOF002' ,
    'INDOOF003' ,
    'INDOOF004' ,
    'INDOOF005' ,
    'INDOOF006' ,
    'INDOOF007' ,
    'INDOOF008' ,
    'INDOOF009' ,
    'INDOOF010' ,
    'INDOOF011' ,
    'INDOOF012' ,
    'INDOOF013' ,
    'INDOOF014' ,
    'INDOOF015' ,
    'INDOOF016' ,
    'INDOOF017' ,
    'INDOOF018' ,
    'INDOOF019' ,
    'INDOOF020' ,
    'INDOOF021' ,
    'INDOOF022' ,
    'INDOOF999' ,
    'INDOON001' ,
    'INDOON002' ,
    'INDOON003' ,
    'INDOON004' ,
    'INDOON005' ,
    'INDOON006' ,
    'INDOON999' ,
    'INDOPC001' ,
    'INDOPC001' ,
    'INDOPC002' ,
    'INDOPC003' ,
    'INDOPC004' ,
    'INDOPC005' ,
    'INDOPC006' ,
    'INDOPC007' ,
    'INDOPC007' ,
    'INDOPC008' ,
    'INDOPC999' ,
    'INDPHA001' ,
    'INDPHA002' ,
    'INDPHA003' ,
    'INDPHA004' ,
    'INDPHA999' ,
    'INDPLA001' ,
    'INDPLA002' ,
    'INDPLA003' ,
    'INDPLA004' ,
    'INDPLA005' ,
    'INDPLA999' ,
    'INDPPR001' ,
    'INDPPR002' ,
    'INDPPR003' ,
    'INDPPR004' ,
    'INDPPR005' ,
    'INDPPR006' ,
    'INDPPR007' ,
    'INDPPR008' ,
    'INDPPR009' ,
    'INDPPR010' ,
    'INDPPR999' ,
    'INDPWR001' ,
    'INDPWR002' ,
    'INDPWR003' ,
    'INDPWR004' ,
    'INDPWR005' ,
    'INDPWR006' ,
    'INDPWR007' ,
    'INDPWR008' ,
    'INDPWR009' ,
    'INDPWR010' ,
    'INDPWR011' ,
    'INDPWR012' ,
    'INDPWR013' ,
    'INDPWR014' ,
    'INDPWR015' ,
    'INDPWR999' ,
    'INDTEL001' ,
    'INDTEL002' ,
    'INDTEL003' ,
    'INDTEL004' ,
    'INDTEL005' ,
    'INDTEL006' ,
    'INDTEL007' ,
    'INDTEL999' ,
    'INDTEX001' ,
    'INDTEX002' ,
    'INDTEX003' ,
    'INDTEX004' ,
    'INDTEX005' ,
    'INDTEX006' ,
    'INDTEX007' ,
    'INDTEX008' ,
    'INDTEX009' ,
    'INDTEX010' ,
    'INDTEX011' ,
    'INDTEX012' ,
    'INDTEX999' ,
    'INDTRN001' ,
    'INDTRN002' ,
    'INDTRN003' ,
    'INDTRN004' ,
    'INDTRN005' ,
    'INDTRN006' ,
    'INDTRN007' ,
    'INDTRN008' ,
    'INDTRN009' ,
    'INDTRN010' ,
    'INDTRN011' ,
    'INDTRN012' ,
    'INDTRN013' ,
    'INDTRN014' ,
    'INDTRN015' ,
    'INDTRN016' ,
    'INDTRN017' ,
    'INDTRN018' ,
    'INDTRN019' ,
    'INDTRN999' ,
    'INDUTY001' ,
    'INDUTY002' ,
    'INDUTY003' ,
    'INDUTY004' ,
    'INDUTY005' ,
    'INDUTY006' ,
    'INDUTY007' ,
    'INDUTY008' ,
    'INDUTY008' ,
    'INDUTY009' ,
    'INDUTY010' ,
    'INDUTY011' ,
    'INDUTY012' ,
    'INDUTY999' ,
    'INDWOD001' ,
    'INDWOD002' ,
    'INDWOD003' ,
    'INDWOD004' ,
    'INDWOD005' ,
    'INDWOD006' ,
    'INDWOD999' ,
    'INFENG001' ,
    'INFENG002' ,
    'INFENG003' ,
    'INFENG004' ,
    'INFENG005' ,
    'INFENG006' ,
    'INFENG007' ,
    'INFENG008' ,
    'INFENG009' ,
    'INFENG010' ,
    'INFENG011' ,
    'INFENG012' ,
    'INFENG013' ,
    'INFENG014' ,
    'INFGEN999' ,
    'MATGEN999' ,
    'MATTRN001' ,
    'MATTRN002' ,
    'MATTRN002' ,
    'MATTRN003' ,
    'MATTRN999' ,
    'MOTFLTF999' ,
    'MOTGEN999' ,
    'RESGEN999' ,
    'RESLRG001' ,
    'RESLRG002' ,
    'RESLRG003' ,
    'RESLRG999' ,
    'RESSML001' ,
    'RESSML002' ,
    'RESSML003' ,
    'RESSML004' ,
    'RESSML005' ,
    'RESSML999' ,
    'UNSUNS999'
];

export const CONSTRUCTION_SCHEME = [
  'RMS',
  'ACCORD',
  'AIR'
];

export const STATES = {
  'Canada' : [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland',
    'Nova Scotia',
    'Northwest Territories',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Yukon Territory'
  ],
  'China' : [
    'SHANGHAI',
    'XINJIANG',
    'XIZANG',
    'HEBEI',
    'LIAONING',
    'JILIN',
    'HEILONGJIANG',
    'SHAANXI',
    'GANSU',
    'QINGHAI',
    'SHANDONG',
    'GUANGXI',
    'JIANGSU',
    'ZHEJIANG',
    'ANHUI',
    'JIANGXI',
    'FUJIAN',
    'HENAN',
    'HUBEI',
    'HUNAN',
    'HAINAN',
    'SICHUAN',
    'BEIJING',
    'GUIZHOU',
    'YUNNAN',
    'SHANXI',
    'ZHONGQING',
    'NEI MONGGOL',
    'GUANGDONG',
    'NINGXIA',
    'TIANJIN',
  ],
  'Spain' : [
    'ANDALUCIA',
    'ARAGON',
    'ASTURIAS',
    'BALEARES',
    'CANARIAS',
    'CANTABRIA',
    'CATALUÑA',
    'CASTILLA-LA-MANCHA',
    'CASTILLA-LEON',
    'CEUTA',
    'EXTREMADURA',
    'GALICIA',
    'MADRID',
    'MELILLA',
    'MURCIA',
    'NAVARRA',
    'PAIS VALENCIANO',
    'PAIS VASCO',
    'LA RIOJA',
  ],
  'France' : [
    'Territoire du sud',
    'France Métropolitaine',
    'Guadeloupe',
    'Guyane Française',
    'Martinique',
    'Mayotte',
    'Nouvelle Calédonie',
    'Polynésie Française',
    'Réunion',
    'Saint Pierre & Miquelon',
    'Wallis & Futuna',
  ],
  'United Kingdom' : [
    'Do Not Use',
    'England',
    'Northern Ireland',
    'Scotland',
    'Wales',
  ],
  'United States of America' : [
    'Alaska',
    'Alabama',
    'Arkansas',
    'Arizona',
    'California',
    'Colorado',
    'Connecticut',
    'Washington, D.C.',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Iowa',
    'Idaho',
    'Illinois',
    'Indiana',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Massachusetts',
    'Maryland',
    'Maine',
    'Michigan',
    'Minnesota',
    'Missouri',
    'Mississippi',
    'Montana',
    'North Carolina',
    'North Dakota',
    'Nebraska',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'Nevada',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Virginia',
    'Vermont',
    'Washington',
    'Wisconsin',
    'West Virginia',
    'Wyoming',
  ]
};

export const COUNTRY = [
    'Afghanistan' ,
    'Aland Islands' ,
    'Albania' ,
    'Algeria' ,
    'American Samoa' ,
    'Andorra' ,
    'Angola' ,
    'Anguilla' ,
    'Antarctica' ,
    'Antigua and Barbuda' ,
    'Argentina' ,
    'Armenia' ,
    'Aruba' ,
    'Australia' ,
    'Austria' ,
    'Azerbaijan' ,
    'Bahamas' ,
    'Bahrain' ,
    'Bangladesh' ,
    'Barbados' ,
    'Belarus' ,
    'Belgium' ,
    'Belize' ,
    'Benin' ,
    'Bermuda' ,
    'Bhutan' ,
    'Bolivia' ,
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island' ,
    'Brazil' ,
    'British Virgin Islands' ,
    'British Indian Ocean Territory' ,
    'Brunei Darussalam' ,
    'Bulgaria' ,
    'Burkina Faso' ,
    'Burundi' ,
    'Cambodia' ,
    'Cameroon' ,
    'Canada' ,
    'Cape Verde' ,
    'Cayman Islands' ,
    'Central African Republic' ,
    'Chad' ,
    'Chile' ,
    'China' ,
    'Hong Kong, SAR China' ,
    'Macao, SAR China' ,
    'Christmas Island' ,
    'Cocos (Keeling) Islands' ,
    'Colombia' ,
    'Comoros' ,
    'Congo (Brazzaville)' ,
    'Congo, (Kinshasa)' ,
    'Cook Islands' ,
    'Costa Rica' ,
    'Côte d Ivoire' ,
    'Croatia' ,
    'Cuba' ,
    'Cyprus' ,
    'Czech Republic' ,
    'Denmark' ,
    'Djibouti' ,
    'Dominica' ,
    'Dominican Republic' ,
    'Ecuador' ,
    'Egypt' ,
    'El Salvador' ,
    'Equatorial Guinea' ,
    'Eritrea' ,
    'Estonia' ,
    'Ethiopia' ,
    'Falkland Islands (Malvinas)' ,
    'Faroe Islands' ,
    'Fiji' ,
    'Finland' ,
    'France' ,
    'French Guiana' ,
    'French Polynesia' ,
    'French Southern Territories' ,
    'Gabon' ,
    'Gambia' ,
    'Georgia' ,
    'Germany' ,
    'Ghana' ,
    'Gibraltar' ,
    'Greece' ,
    'Greenland' ,
    'Grenada' ,
    'Guadeloupe' ,
    'Guam' ,
    'Guatemala' ,
    'Guernsey' ,
    'Guinea' ,
    'Guinea-Bissau' ,
    'Guyana' ,
    'Haiti' ,
    'Heard and Mcdonald Islands' ,
    'Holy See (Vatican City State)' ,
    'Honduras' ,
    'Hungary' ,
    'Iceland' ,
    'India' ,
    'Indonesia' ,
    'Iran, Islamic Republic of' ,
    'Iraq' ,
    'Ireland' ,
    'Isle of Man' ,
    'Israel' ,
    'Italy' ,
    'Jamaica' ,
    'Japan' ,
    'Jersey' ,
    'Jordan' ,
    'Kazakhstan' ,
    'Kenya' ,
    'Kiribati' ,
    'Korea (North)' ,
    'Korea (South)' ,
    'Kuwait' ,
    'Kyrgyzstan' ,
    'Lao PDR' ,
    'Latvia' ,
    'Lebanon' ,
    'Lesotho' ,
    'Liberia' ,
    'Libya' ,
    'Liechtenstein' ,
    'Lithuania' ,
    'Luxembourg' ,
    'Macedonia, Republic of' ,
    'Madagascar' ,
    'Malawi' ,
    'Malaysia' ,
    'Maldives' ,
    'Mali' ,
    'Malta' ,
    'Marshall Islands' ,
    'Martinique' ,
    'Mauritania' ,
    'Mauritius' ,
    'Mayotte' ,
    'Mexico' ,
    'Micronesia, Federated States of' ,
    'Moldova' ,
    'Monaco' ,
    'Mongolia' ,
    'Montenegro' ,
    'Montserrat' ,
    'Morocco' ,
    'Mozambique' ,
    'Myanmar' ,
    'Namibia' ,
    'Nauru' ,
    'Nepal' ,
    'Netherlands' ,
    'Netherlands Antilles' ,
    'New Caledonia' ,
    'New Zealand' ,
    'Nicaragua' ,
    'Niger' ,
    'Nigeria' ,
    'Niue' ,
    'Norfolk Island' ,
    'Northern Mariana Islands' ,
    'Norway' ,
    'Oman' ,
    'Pakistan' ,
    'Palau' ,
    'Palestinian Territory' ,
    'Panama' ,
    'Papua New Guinea' ,
    'Paraguay' ,
    'Peru' ,
    'Philippines' ,
    'Pitcairn' ,
    'Poland' ,
    'Portugal' ,
    'Puerto Rico' ,
    'Qatar' ,
    'Réunion' ,
    'Romania' ,
    'Russian Federation' ,
    'Rwanda' ,
    'Saint-Barthélemy' ,
    'Saint Helena' ,
    'Saint Kitts and Nevis' ,
    'Saint Lucia' ,
    'Saint-Martin (French part)' ,
    'Saint Pierre and Miquelon' ,
    'Saint Vincent and Grenadines' ,
    'Samoa' ,
    'San Marino' ,
    'Sao Tome and Principe' ,
    'Saudi Arabia' ,
    'Senegal' ,
    'Serbia' ,
    'Seychelles' ,
    'Sierra Leone' ,
    'Singapore' ,
    'Slovakia' ,
    'Slovenia' ,
    'Solomon Islands' ,
    'Somalia' ,
    'South Africa' ,
    'South Georgia and the South Sandwich Islands' ,
    'South Sudan' ,
    'Spain' ,
    'Sri Lanka' ,
    'Sudan' ,
    'Suriname' ,
    'Svalbard and Jan Mayen Islands',
    'Swaziland' ,
    'Sweden' ,
    'Switzerland' ,
    'Syrian Arab Republic (Syria)' ,
    'Taiwan, Republic of China' ,
    'Tajikistan' ,
    'Tanzania, United Republic of' ,
    'Thailand' ,
    'Timor-Leste' ,
    'Togo' ,
    'Tokelau' ,
    'Tonga' ,
    'Trinidad and Tobago' ,
    'Tunisia' ,
    'Turkey' ,
    'Turkmenistan' ,
    'Turks and Caicos Islands' ,
    'Tuvalu' ,
    'Uganda' ,
    'Ukraine' ,
    'United Arab Emirates' ,
    'United Kingdom' ,
    'United States of America' ,
    'US Minor Outlying Islands' ,
    'Uruguay' ,
    'Uzbekistan' ,
    'Vanuatu' ,
    'Venezuela (Bolivarian Republic)' ,
    'Viet Nam' ,
    'Virgin Islands, US' ,
    'Wallis and Futuna Islands' ,
    'Western Sahara' ,
    'Yemen' ,
    'Zambia' ,
    'Zimbabwe'
];

export const STATE = [
    'Alberta' ,
    'British Columbia' ,
    'Manitoba' ,
    'New Brunswick' ,
    'Newfoundland' ,
    'Nova Scotia' ,
    'Northwest Territories' ,
    'Nunavut' ,
    'Ontario' ,
    'Prince Edward Island' ,
    'Quebec' ,
    'Saskatchewan' ,
    'Yukon Territory' ,
    'SHANGHAI' ,
    'XINJIANG' ,
    'XIZANG' ,
    'HEBEI' ,
    'LIAONING' ,
    'JILIN' ,
    'HEILONGJIANG' ,
    'SHAANXI' ,
    'GANSU' ,
    'QINGHAI' ,
    'SHANDONG' ,
    'GUANGXI' ,
    'JIANGSU' ,
    'ZHEJIANG' ,
    'ANHUI' ,
    'JIANGXI' ,
    'FUJIAN' ,
    'HENAN' ,
    'HUBEI' ,
    'HUNAN' ,
    'HAINAN' ,
    'SICHUAN' ,
    'BEIJING' ,
    'GUIZHOU' ,
    'YUNNAN' ,
    'SHANXI' ,
    'ZHONGQING' ,
    'NEI MONGGOL' ,
    'GUANGDONG' ,
    'NINGXIA' ,
    'TIANJIN' ,
    'ANDALUCIA',
    'ARAGON' ,
    'ASTURIAS' ,
    'BALEARES' ,
    'CANARIAS' ,
    'CANTABRIA' ,
    'CATALUÑA' ,
    'CASTILLA-LA-MANCHA' ,
    'CASTILLA-LEON' ,
    'CEUTA' ,
    'EXTREMADURA' ,
    'GALICIA' ,
    'MADRID' ,
    'MELILLA' ,
    'MURCIA' ,
    'NAVARRA' ,
    'PAIS VALENCIANO' ,
    'PAIS VASCO' ,
    'LA RIOJA' ,
    'Territoire du sud' ,
    'France Métropolitaine' ,
    'Guadeloupe' ,
    'Guyane Française' ,
    'Martinique' ,
    'Mayotte' ,
    'Nouvelle Calédonie' ,
    'Polynésie Française' ,
    'Réunion' ,
    'Saint Pierre & Miquelon' ,
    'Wallis & Futuna' ,
    'Do Not Use' ,
    'England' ,
    'Do Not Use' ,
    'Northern Ireland' ,
    'Scotland' ,
    'Wales' ,
    'Alaska' ,
    'Alabama' ,
    'Arkansas' ,
    'Arizona' ,
    'California' ,
    'Colorado' ,
    'Connecticut' ,
    'Washington, D.C.' ,
    'Delaware' ,
    'Florida' ,
    'Georgia' ,
    'Hawaii' ,
    'Iowa' ,
    'Idaho' ,
    'Illinois' ,
    'Indiana' ,
    'Kansas' ,
    'Kentucky' ,
    'Louisiana' ,
    'Massachusetts' ,
    'Maryland' ,
    'Maine' ,
    'Michigan' ,
    'Minnesota' ,
    'Missouri' ,
    'Mississippi' ,
    'Montana' ,
    'North Carolina' ,
    'North Dakota' ,
    'Nebraska' ,
    'New Hampshire' ,
    'New Jersey' ,
    'New Mexico' ,
    'Nevada' ,
    'New York' ,
    'Ohio' ,
    'Oklahoma' ,
    'Oregon' ,
    'Pennsylvania' ,
    'Puerto Rico' ,
    'Rhode Island' ,
    'South Carolina' ,
    'South Dakota' ,
    'Tennessee' ,
    'Texas' ,
    'Utah' ,
    'Virginia' ,
    'Vermont' ,
    'Washington' ,
    'Wisconsin' ,
    'West Virginia' ,
    'Wyoming' ,
    'Arkansas' ,
    'Iowa' ,
    'Illinois' ,
    'Indiana' ,
    'Kansas' ,
    'Kentucky' ,
    'Michigan' ,
    'Minnesota' ,
    'Missouri' ,
    'North Dakota' ,
    'Nebraska' ,
    'Ohio' ,
    'Oklahoma' ,
    'South Dakota' ,
    'Tennessee' ,
    'Wisconsin' ,
    'Connecticut' ,
    'Massachusetts' ,
    'Maine' ,
    'New Hampshire' ,
    'Rhode Island' ,
    'Vermont' ,
    'Alaska' ,
    'Arizona' ,
    'California' ,
    'Colorado' ,
    'Hawaii' ,
    'Idaho' ,
    'Montana' ,
    'New Mexico' ,
    'Nevada' ,
    'Oregon' ,
    'Utah' ,
    'Washington' ,
    'Wyoming' ,
    'Washington, D.C.' ,
    'Delaware' ,
    'Maryland' ,
    'New Jersey' ,
    'New York' ,
    'Pennsylvania' ,
    'Virginia' ,
    'West Virginia' ,
    'Florida' ,
    'Georgia' ,
    'North Carolina' ,
    'South Carolina' ,
    'Alabama' ,
    'Louisiana' ,
    'Mississippi' ,
    'Texas' ,
];

export const ACCORD_OCCUPANCY_CLASS = [
        'Agriculture Cultivation' ,
        'General' ,
        'Agriculture infrastructure' ,
        'Administration, commercial service, public facility' ,
        'Large commercial' ,
        'Public, educational, religious building' ,
        'Retail, trading, storage facility' ,
        'Small commercial' ,
        'Civil work and special engineering structure' ,
        'Chemicals' ,
        'Electric, electronic,  high precision work' ,
        'Food, beverage, tobacco' ,
        'Heavy industrial' ,
        'Light industrial' ,
        'Metal and machinery' ,
        'Mining, steel, foundry, rolling mill' ,
        'Non metallic mineral products' ,
        'Oil and gas extraction offshor' ,
        'Oil and gas extraction onshore' ,
        'Oil and petrochemicals' ,
        'Pharmaceuticals, biotec' ,
        'Plastic and rubber' ,
        'Pulp and paper, printing' ,
        'Power generation and distribution' ,
        'Telecommunication and data processing' ,
        'Textile and leather' ,
        'Transportation services, repair, maintenance' ,
        'Utilities excluding power generatio' ,
        'Wood' ,
        'Civil work and special engineering structure' ,
        'Transportatio' ,
        'Car and motor fleet (hull)' ,
        'large residential' ,
        'Unspecified'
];

export const ACCORD_OCCUPANCY_SUB_CLASS = [
    'Animal husbandry' ,
    'Crop' ,
   'Fish' ,
   'Forest' ,
   'Fruits' ,
   'Greenhouse' ,
   'Nursery' ,
   'Barn' ,
   'Farmhouse' ,
   'Bar, pub, club, tavern, discotheque' ,
   'Casino, Theatre, Cinema' ,
   'Floating casino' ,
   'Hospital' ,
   'Hotel' ,
   'Medical day care centre' ,
   'Motel',
   'Nursing home' ,
   'Office building' ,
   'Restaurant' ,
   'Vacation resort, golf course' ,
   'Amusement park' ,
   'Cinema, concert hall, theatre' ,
   'Convention centre' ,
   'Exhibition hall' ,
   'Film, television, radio studio' ,
   'Library' ,
   'Museum' ,
   'Prison or jail' ,
   'Religious building (church, mosque, synagogue, temple, monastery, etc...)' ,
   'School' ,
   'Stadium, arena' ,
   'Temporary exhibition facility or circus' ,
   'University or college (including dormitories)' ,
   'Cold storage - warehouse' ,
   'Department store including retail trade' ,
   'Distribution centre' ,
   'High hazardous goods storage - warehouse' ,
   'Low hazardous goods storage - warehouse' ,
   'Market hall' ,
   'Medium hazardous goods storage - warehouse' ,
   'Open-air storage yard' ,
   'Petrol or liquefied petroleum gas (LPG) station' ,
   'Shopping centre or strip mall' ,
   'Silo' ,
   'Supermarket' ,
   'Wholesale trading store' ,
   'Ammonia or ammonium nitrate based fertiliser plant' ,
   'An organic fertiliser plant (triple super phosphate, potassium, etc...)' ,
   'Aromatic oils and essences production - chemical plant' ,
   'Bone glue - chemical plant' ,
   'Candles or wax manufacturing (excluding base stock) - chemical plant' ,
   'Coatings: powder - chemical plant' ,
   'Coatings: solvent based - chemical plant' ,
   'Coatings: water based - chemical plant' ,
   'Hydrogen peroxide, persulfate, etc...- chemical plant' ,
   'Lubricant manufacturing (excluding base stock) - chemical plant' ,
   'Mixing and blending of industrial gases: with cold box - chemical plant' ,
   'Mixing and blending of industrial gases: without cold box - chemical plant' ,
   'Other specialty chemicals - chemical plant' ,
   'Other synthetic fibres (polyester, nylon fibres, etc...) - chemical plant' ,
   'Perfumes or cosmetics - chemical plant' ,
   'Pesticides with nitrate reactions - chemical plant' ,
   'Pesticides, herbicides, fungicides, other biocides - chemical plant' ,
   'Pigments - chemical plant' ,
   'Primary explosives (pyrotechnics, fireworks, detonators) - chemical plant' ,
   'Resins, latex paints, adhesives - chemical plant' ,
   'Secondary explosives (ammunition, blasting agent) - chemical plant' ,
   'Soaps, detergents, polishes, chlorine based bleaching agents - chemical plant' ,
   'Viscose - chemical plant' ,
   'Assembly with clean room (back end production) - semiconductor plant' ,
   'Batteries and accumulators manufacturing plant' ,
   'Electric motors, machines, appliances manufacturing plant' ,
   'Jewellery, goldsmith, precious stone - manufacturing plant' ,
   'Light bulbs factory' ,
   'Manufacturing with clean room (front end production, wafer fab) - semiconductor plant' ,
   'Manufacturing, assembly plant for electronic or high tech products: with clean room' ,
   'Manufacturing, assembly plant for electronic or high tech products: without clean room' ,
   'Mass and custom software (burning of CD,  DVD, packaging) - manufacturing plant' ,
   'Optics, telescope, camera, laser manufacturing plant' ,
   'Watches factory' ,
   'Bakery' ,
   'Brewery or winery' ,
   'Chocolate factory' ,
   'Cigarette or cigar factory' ,
   'Coffee roasting facility or malthouse' ,
   'Dairy products and milk processing plant: with milk powder' ,
   'Dairy products and milk processing plant: without milk powder' ,
   'Distillery' ,
   'Edible fat or oil processing plant (without oil milling)' ,
   'Fruits and vegetables processing factory (including fruit pressing for juice)' ,
   'Ice factory' ,
   'Meat, fish drying and preservation plant' ,
   'Meat, fish processing plant' ,
   'Mill: feed, flour, grain, etc...' ,
   'Non-alcoholic beverage plant (mixing and bottling)' ,
   'Non-alcoholic beverage plant (mixing and bottling)' ,
   'Oil milling and processing plant: no solvent extraction' ,
   'Oil milling and processing plant: with solvent extraction' ,
   'Other processed food  factory (food preparation, catering, etc...)' ,
   'Slaughter house, abattoir, rendering plant' ,
   'Starch factory' ,
   'Sugar refinery' ,
   'Aircraft manufacturing plant' ,
   'Automobile, heavy vehicles assembly and manufacturing plant (original equipment manufacturer - OEM)' ,
   'Cable factory including plastic insulation' ,
   'Heavy machinery production or assembly plant (pumps, compressors, turbines, etc...)' ,
   'Light machinery production, assembly plant (including non electric engines)' ,
   'Metal surface treatment (galvanising, pickling, hardening, etc...) - metal products factory' ,
   'Metal working and assembly (light metal working) - metal products factory' ,
   'Non ferrous metal processing - metal products factory' ,
   'Railway vehicle manufacturing plant' ,
   'Satellites and spacecrafts manufacturing plant (excluding rocket motors)' ,
   'Shipbuilding and vessel manufacturing shipyard' ,
   'Wire factory (bare wire)' ,
   'Alumina refinery' ,
   'Aluminium smelter' ,
   'Brine solution mine' ,
   'Brine solution mine' ,
   'Brine solution mine' ,
   'Coal wash plant' ,
   'Coal wash plant' ,
   'Coking plant' ,
   'Integrated steel plant with blast furnace' ,
   'Integrated steel plant with direct reduction' ,
   'Iron or steel foundry' ,
   'Iron or steel foundry' ,
   'Mini mill' ,
   'Ore processing plant with solvent extraction' ,
   'Ore processing plant with solvent extraction' ,
   'Ore processing plant with solvent extraction' ,
   'Ore processing plant without solvent extraction' ,
   'Ore processing plant without solvent extraction' ,
   'Other foundry (other than steel or aluminium)' ,
   'Peat mine (extraction, processing)' ,
   'Quarry (stone, gravel, sand extraction and processing)' ,
   'Rolling mill (all metals)' ,
   'Salt, potash mine: surface' ,
   'Salt, potash mine: underground' ,
   'Sea bed mining site (shallow or deep)' ,
   'Surface coal mine' ,
   'Surface mine excluding coal (extraction, concentration)' ,
   'Surface mine excluding coal (extraction, concentration)' ,
   'Underground coal mine' ,
   'Underground mine excluding coal (extraction, concentration)' ,
   'Asphalt mixture (block and paving) factory' ,
   'Brick or tile factory' ,
   'Cement or plaster products factory with oven' ,
   'Cement or plaster products factory without oven' ,
   'Cement production site with rotary kiln' ,
   'Ceramics or earthenware factory' ,
   'Coated shingle factory' ,
   'Concrete parts factory (prefabrication)' ,
   'Emery or abrasive products' ,
   'Glass sheet factory for flat screen display devices' ,
   'Hollow glass or glass bottles factory' ,
   'Insulation material factory (mineral, glass wool, etc...)' ,
   'Lightweight slab factory' ,
   'Lime or gypsum products factory' ,
   'Mirror factory' ,
   'Roofing felt factory' ,
   'Sandwich panel factory: glass, rock' ,
   'Sandwich panel factory: polyurethane(PUR), polyisocyanurate (PIR), expanded polystyrene (EPS)' ,
   'Sheet or plate glass factory' ,
   'Stone slab or paving stone factory' ,
   'Tarboard or tar paper factory' ,
   'Barge, support vessel, seismic vessel' ,
   'Buoy (single point mooring - SPM, catenary anchor leg mooring - CALM)' ,
   'Crane barge or pipelay vessel' ,
   'Drill ship' ,
   'Floating liquefied natural gas (LNG), gas to liquid (GTL) vessel' ,
   'Floating, production, storage and off-loading vessel (FPSO)' ,
   'Floating, storage and off-loading vessel (FSO)' ,
   'Offshore complex (bridge linked fixed steel structures)' ,
   'Offshore concrete gravity based structure' ,
   'Offshore fixed steel structure' ,
   'Offshore pipeline: deep (> 200m and <= 1500m)' ,
   'Offshore pipeline: shallow (<= 200m)' ,
   'Offshore pipeline: ultra deep ( > 1500m)' ,
   'Other floating production systems' ,
   'Self elevating jack-up with independent legs' ,
   'Self elevating jack-up with mat base' ,
   'Semi submersible drilling rig' ,
   'Semi submersible production platform' ,
   'Spar or tension leg platform' ,
   'Subsea equipment: deep (> 200m and <= 1500m)' ,
   'Subsea equipment: shallow (< 200 m)' ,
   'Subsea equipment: ultra deep ( > 1500m)' ,
   'Land rig' ,
   'Onshore pipeline' ,
   'Onshore pipeline: pipeline compressor station' ,
   'Onshore pipeline: pumping station' ,
   'Onshore pipeline: river crossings' ,
   'Onshore production facility (well heads, separation stations, gathering station, etc...)' ,
   'Gas plant' ,
   'Hydrocarbon underground storage and associated surface infrastructure' ,
   'Liquefied natural gas (LNG) or liquefied petroleum gas (LPG) plant' ,
   'Oil and petro terminal' ,
   'Oil refinery' ,
   'Petrochemicals plant (including plastic fabrication out of monomere)' ,
   'Tank farm' ,
   'Upgrader (tar sands)' ,
   'Packaging, tableting, formulation - pharmaceutical plant' ,
   'Pharma intermediates, food additives, vitamins, preservatives - pharmaceutical plant' ,
   'R&D laboratory (pharmaceuticals or biotechnology)' ,
   'Synthetic production (active pharmaceutical ingredients - API) - pharmaceutical plant' ,
   'Extrusion, injection moulding of plastic products - plastic goods factory' ,
   'Foam no polyurethane (excluding manufacturing out of monomere) - plastic goods factory' ,
   'Foam polyurethane (excluding manufacturing out of monomeres) - plastic goods factory' ,
   'Rubber goods factory' ,
   'Tyre factory' ,
   'Cardboard or paper goods factory' ,
   'Chemical pulp mill with black liquor recovery boiler (BLRB) or sulphites' ,
   'Integrated paper mill (pulping including black liquor recovery boiler (BLRB) and paper production)' ,
   'Mechanical pulp mill' ,
   'Paper mill without pulp production' ,
   'Paper recycling plant' ,
   'Printing plant: combined' ,
   'Printing plant: solvent based' ,
   'Printing plant: water based' ,
   'Tissue mill without pulp production' ,
   'Aeolic power plant or wind farm: onshore' ,
   'Aeolic power plant or windfarm: offshore' ,
   'Biomass power plant' ,
   'Combined cycle gas turbine power plant' ,
   'Conventional steam, coal fired power plant' ,
   'Conventional steam, oil or gas fired power plant' ,
   'Geothermal power plant' ,
   'Hydro power plant' ,
   'Nuclear power plant' ,
   'Overhead power line' ,
   'Power distribution: substation' ,
   'Simple cycle gas turbine power plant' ,
   'Solar power plant: concentration' ,
   'Solar power plant: photovoltaic' ,
   'Underground power line' ,
   'Electronic data processing (EDP) centre, call centre' ,
   'Radio or television broadcasting station' ,
   'Submarine, underground cable' ,
   'Switching centre' ,
   'Telecom, television tower, antenna for wireless network' ,
   'Overhead telecommunication line' ,
   'Underground telecommunication line' ,
   'Carpet, rope, string production plant' ,
   'Clothing,  other cloth products including  textile recycling - textile factory' ,
   'Finishing of textiles - textile factory' ,
   'Leather factory' ,
   'Natural fibre (cotton, kapok, wool) -  textile production plant' ,
   'Non woven fabrics (cotton wool, fleece, felts) - textile factory' ,
   'Shoe factory' ,
   'Spinning, prespinning processes - textile factory' ,
   'Tannery' ,
   'Textile cleaning shop (launderette, laundromat, dry cleaning shop, etc...)' ,
   'Upholstery or mattress factory' ,
   'Weaving or twisting -  textile factory' ,
   'Air traffic control centre' ,
   'Aircraft hangar without maintenance' ,
   'Aircraft maintenance hangar' ,
   'Airport terminal' ,
   'Bus, taxi, truck maintenance garage' ,
   'Cable railway infrastructure (excluding bridges and tunnels)' ,
   'Covered above ground parking garage or yard (including high rise garage)' ,
   'Dock or port crane' ,
   'General airport services (excluding airport terminals)' ,
   'Harbour, terminal for containers, storage (grain, coal,  minerals)' ,
   'Maritime traffic infrastructure (ferry station, shipyard, etc...)' ,
   'Parking yard (not covered)' ,
   'Port terminal for passengers' ,
   'Railway station' ,
   'Road traffic services, station, operation centre' ,
   'Road vehicles or construction machines maintenance garage' ,
   'Rolling stock maintenance workshop' ,
   'Ships and vessels maintenance shipyard' ,
   'Underground parking garage' ,
   'Desalination plant' ,
   'District heating (water, steam heating)' ,
   'Drinking or waste water lines' ,
   'Fresh water procurement or treatment plant' ,
   'Gas distribution network' ,
   'Landfill site' ,
   'Recycling plant' ,
   'Waste incineration plant' ,
   'Waste incineration plant' ,
   'Waste water treatment plant' ,
   'Water  tower' ,
   'Water pumping station' ,
   'Water reservoir' ,
   'Forestry infrastructure (machinery, buildings, etc...)' ,
   'Furniture, wooden goods workshop' ,
   'Sawmill' ,
   'Wood board, particle board, plywood factory' ,
   'Wood chips, wood pellets production plant' ,
   'Wood preservation workshop' ,
   'Alluvium tunnel' ,
   'Bridge' ,
   'Building contractor installations: above ground construction' ,
   'Building contractor installations: underground construction' ,
   'Concrete dam' ,
   'Cut and cover tunnel, gallery' ,
   'Earth and rockfill dam' ,
   'Railway track, infrastructure (excluding bridges, tunnels, rolling stock)' ,
   'Road or highway' ,
   'Rock tunnel' ,
   'Runway' ,
   'Span bridge' ,
   'Waterfront structure' ,
   'Waterways inland' ,
   'Aircraft (hull)' ,
   'Rolling stock (railway infrastructure, trains)' ,
   'Rolling stock (railway infrastructure, trains)' ,
   'Ship or vessel (hull)' ,
   'multi-family housing' ,
   'group institutional housing' ,
   'terraced housing' ,
   'single family housing' ,
   'multi-family housing' ,
   'attached housing' ,
   'semi-attached housing' ,
   'mobile home',
   'Unspecified'
];

export const ISO_2 = [
  'AF',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BA',
  'BW',
  'BV',
  'BR',
  'VG',
  'IO',
  'BN',
  'BG',
  'BF',
  'BI',
  'KH',
  'CM',
  'CA',
  'CV',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'HK',
  'MO',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'CK',
  'CR',
  'CI',
  'HR',
  'CU',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MK',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'ME',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'AN',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'RE',
  'RO',
  'RU',
  'RW',
  'BL',
  'SH',
  'KN',
  'LC',
  'MF',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SZ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'US',
  'UM',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'VI',
  'WF',
  'EH',
  'YE',
  'ZM',
  'ZW',
];

export const ISO_3 = [
  'AFG' ,
  'ALA' ,
  'ALB' ,
  'DZA' ,
  'ASM' ,
  'AND' ,
  'AGO' ,
  'AIA' ,
  'ATA' ,
  'ATG' ,
  'ARG' ,
  'ARM' ,
  'ABW' ,
  'AUS' ,
  'AUT' ,
  'AZE' ,
  'BHS' ,
  'BHR' ,
  'BGD' ,
  'BRB' ,
  'BLR' ,
  'BEL' ,
  'BLZ' ,
  'BEN' ,
  'BMU' ,
  'BTN' ,
  'BOL' ,
  'BIH' ,
  'BWA' ,
  'BVT' ,
  'BRA' ,
  'VGB' ,
  'IOT' ,
  'BRN' ,
  'BGR' ,
  'BFA' ,
  'BDI' ,
  'KHM' ,
  'CMR' ,
  'CAN' ,
  'CPV' ,
  'CYM' ,
  'CAF' ,
  'TCD' ,
  'CHL' ,
  'CHN' ,
  'HKG' ,
  'MAC' ,
  'CXR' ,
  'CCK' ,
  'COL' ,
  'COM' ,
  'COG' ,
  'COD' ,
  'COK' ,
  'CRI' ,
  'CIV' ,
  'HRV' ,
  'CUB' ,
  'CYP' ,
  'CZE' ,
  'DNK' ,
  'DJI' ,
  'DMA' ,
  'DOM' ,
  'ECU' ,
  'EGY' ,
  'SLV' ,
  'GNQ' ,
  'ERI' ,
  'EST' ,
  'ETH' ,
  'FLK' ,
  'FRO' ,
  'FJI' ,
  'FIN' ,
  'FRA' ,
  'GUF' ,
  'PYF' ,
  'ATF' ,
  'GAB' ,
  'GMB' ,
  'GEO' ,
  'DEU' ,
  'GHA' ,
  'GIB' ,
  'GRC' ,
  'GRL' ,
  'GRD' ,
  'GLP' ,
  'GUM' ,
  'GTM' ,
  'GGY' ,
  'GIN' ,
  'GNB' ,
  'GUY' ,
  'HTI' ,
  'HMD' ,
  'VAT' ,
  'HND' ,
  'HUN' ,
  'ISL' ,
  'IND' ,
  'IDN' ,
  'IRN' ,
  'IRQ' ,
  'IRL' ,
  'IMN' ,
  'ISR' ,
  'ITA' ,
  'JAM' ,
  'JPN' ,
  'JEY' ,
  'JOR' ,
  'KAZ' ,
  'KEN' ,
  'KIR' ,
  'PRK' ,
  'KOR' ,
  'KWT' ,
  'KGZ' ,
  'LAO' ,
  'LVA' ,
  'LBN' ,
  'LSO' ,
  'LBR' ,
  'LBY' ,
  'LIE' ,
  'LTU' ,
  'LUX' ,
  'MKD' ,
  'MDG' ,
  'MWI' ,
  'MYS' ,
  'MDV' ,
  'MLI' ,
  'MLT' ,
  'MHL' ,
  'MTQ' ,
  'MRT' ,
  'MUS' ,
  'MYT' ,
  'MEX' ,
  'FSM' ,
  'MDA' ,
  'MCO' ,
  'MNG' ,
  'MNE' ,
  'MSR' ,
  'MAR' ,
  'MOZ' ,
  'MMR' ,
  'NAM' ,
  'NRU' ,
  'NPL' ,
  'NLD' ,
  'ANT' ,
  'NCL' ,
  'NZL' ,
  'NIC' ,
  'NER' ,
  'NGA' ,
  'NIU' ,
  'NFK' ,
  'MNP' ,
  'NOR' ,
  'OMN' ,
  'PAK' ,
  'PLW' ,
  'PSE' ,
  'PAN' ,
  'PNG' ,
  'PRY' ,
  'PER' ,
  'PHL' ,
  'PCN' ,
  'POL' ,
  'PRT' ,
  'PRI' ,
  'QAT' ,
  'REU' ,
  'ROU' ,
  'RUS' ,
  'RWA' ,
  'BLM' ,
  'SHN' ,
  'KNA' ,
  'LCA' ,
  'MAF' ,
  'SPM' ,
  'VCT' ,
  'WSM' ,
  'SMR' ,
  'STP' ,
  'SAU' ,
  'SEN' ,
  'SRB' ,
  'SYC' ,
  'SLE' ,
  'SGP' ,
  'SVK' ,
  'SVN' ,
  'SLB' ,
  'SOM' ,
  'ZAF' ,
  'SGS' ,
  'SSD' ,
  'ESP' ,
  'LKA' ,
  'SDN' ,
  'SUR' ,
  'SJM' ,
  'SWZ' ,
  'SWE' ,
  'CHE' ,
  'SYR' ,
  'TWN' ,
  'TJK' ,
  'TZA' ,
  'THA' ,
  'TLS' ,
  'TGO' ,
  'TKL' ,
  'TON' ,
  'TTO' ,
  'TUN' ,
  'TUR' ,
  'TKM' ,
  'TCA' ,
  'TUV' ,
  'UGA' ,
  'UKR' ,
  'ARE' ,
  'GBR' ,
  'USA' ,
  'UMI' ,
  'URY' ,
  'UZB' ,
  'VUT' ,
  'VEN' ,
  'VNM' ,
  'VIR' ,
  'WLF' ,
  'ESH' ,
  'YEM' ,
  'ZMB' ,
  'ZWE'
];

export const ASSET_QUALITY = [
'Poor',
'Below average',
'Average Minus',
'Average',
'Average Plus',
'Above Average',
'Good'
];

export const MB_QUALITY = [
'Poor',
'Below average',
'Average Minus',
'Average',
'Average Plus',
'Above Average',
'Good'
];

export const BI_MITIGATION = [
'Poor',
'Below average',
'Average Minus',
'Average',
'Average Plus',
'Above Average',
'Good'
];

export const ACCURACY_LEVEL = [
  'Unkown' ,
  'Country' ,
  'Region' ,
  'Sub-region' ,
  'Town' ,
  'Post Code' ,
  'Street' ,
  'Intersection' ,
  'Address' ,
  'Premise'
];

export const GEOCODER = [
  'Here',
  'Trillium',
  'SCOR Data base',
  'Property DB' ,
];

export const ACCURACY_VALIDATED = [
  'Yes',
  'No'
];

export const BI_TYPE = [
  'Loss of Profits',
  'Gross Earnings',
  'Standing Charges'
];

export const FOR_INTEREST = [
   '100',
   'For Interest'
];

export const CURRENCY =  [
  'CURR',
  'ADP',
  'AED',
  'AFA',
  'AFN',
  'ALK',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'AOK',
  'AON',
  'AOR',
  'AR1',
  'AR2',
  'AR3',
  'AR6',
  'AR7',
  'ARA',
  'ARP',
  'ARS',
  'ARY',
  'ATS',
  'AUD',
  'AUS',
  'AWG',
  'AZN',
  'BBD',
  'BDT',
  'BEF',
  'BEL',
  'BGL',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BO1',
  'BOB',
  'BOP',
  'BRB',
  'BRC',
  'BRE',
  'BRL',
  'BRN',
  'BRR',
  'BSD',
  'BTN',
  'BUK',
  'BWP',
  'BYR',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLD',
  'CLF',
  'CLP',
  'CLU',
  'CNY',
  'COP',
  'CRC',
  'CSD',
  'CSK',
  'CUP',
  'CVE',
  'CYP',
  'CZK',
  'DDM',
  'DEM',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'ECS',
  'EEK',
  'EGP',
  'ESP',
  'ETB',
  'EUH',
  'EUR',
  'FIM',
  'FJD',
  'FKP',
  'FR1',
  'FRC',
  'FRF',
  'FTR',
  'GBP',
  'GEL',
  'GHC',
  'GHS',
  'GMD',
  'GNE',
  'GNF',
  'GNS',
  'GRD',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRD',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'IEP',
  'IKR',
  'ILO',
  'ILP',
  'ILR',
  'ILS',
  'INR',
  'IQD',
  'IRR',
  'ISA',
  'ISJ',
  'ISK',
  'ITL',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAJ',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LSM',
  'LTL',
  'LUF',
  'LUL',
  'LVL',
  'LYD',
  'MAD',
  'MAF',
  'MDL',
  'MFF',
  'MGA',
  'MGF',
  'MKD',
  'MKK',
  'MLF',
  'MMK',
  'MNT',
  'MOP',
  'MRO',
  'MTL',
  'MTP',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MXP',
  'MXV',
  'MYR',
  'MZM',
  'MZN',
  'NAD',
  'NBC',
  'NGN',
  'NIA',
  'NIB',
  'NIC',
  'NIO',
  'NLG',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEH',
  'PEI',
  'PEN',
  'PES',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PLZ',
  'PSO',
  'PTE',
  'PYG',
  'QAR',
  'RCL',
  'RHD',
  'ROL',
  'RON',
  'RSD',
  'RUB',
  'RUR',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDD',
  'SDG',
  'SDP',
  'SEK',
  'SGD',
  'SIT',
  'SKK',
  'SLL',
  'SOL',
  'SOS',
  'SRD',
  'SRG',
  'SSP',
  'STD',
  'SUR',
  'SVC',
  'SYP',
  'SZL',
  'THB',
  'TND',
  'TOP',
  'TRK',
  'TRL',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UCS',
  'UDS',
  'UGS',
  'UGW',
  'UGX',
  'UPR',
  'USD',
  'UYN',
  'UYP',
  'UYU',
  'VEB',
  'VEF',
  'VN1',
  'VNC',
  'VND',
  'VUV',
  'WST',
  'XA2',
  'XA5',
  'XAF',
  'XBD',
  'XC1',
  'XCD',
  'XEU',
  'XO2',
  'XO3',
  'XOF',
  'XPF',
  'XXB',
  'XXC',
  'XXE',
  'XXK',
  'XXL',
  'XXM',
  'XXN',
  'XXO',
  'XXP',
  'XXQ',
  'XXR',
  'XXS',
  'XXT',
  'XXU',
  'XXV',
  'XXW',
  'YDD',
  'YEM',
  'YER',
  'YUD',
  'YUM',
  'YUN',
  'ZAR',
  'ZMK',
  'ZRM',
  'ZRN',
  'ZRZ',
  'ZWD',
  'ZWL',
  'ZWN',
  'ZWR',
  'ZMW',
  'CNH',
  'MRU',
  'UZS',
];

export const UNIT = [
  'One',
  'Thousands',
  'Millions',
];

export const UNITVALUES = {
  'One' : 1,
  'Thousands': 1000,
  'Millions': 1000000,
};

export const PRICING_CATEGORY = [
  'Other categories',
  'Leisure industry',
  'Public buildings',
  'Commercial buildings',
  'Warehouse',
  'Midstream - Transportation/Storage',
  'Infrastructure',
  'Chemicals',
  'Specialty chemicals',
  'High Tech Industries',
  'Mechanical industries',
  'Food producers',
  'Beverage producers',
  'Tobacco',
  'Aerospace & Defence',
  'Automotive & Parts',
  'Metal Works',
  'Railway manufacturing industry',
  'Metallurgy',
  'Mining - Bulk commodities',
  'Building materials',
  'Mining - Other',
  'Mining - Hard Rock',
  'Mining - Underground coal',
  'Glass/ Ceramic/Others',
  'Other Onshore',
  'Gas Processing',
  'Crude Processing - Refining',
  'Petrochemical',
  'Pharmaceuticals & fine chemicals',
  'Rubber & Plastic Manufacturing',
  'Pulp & paper',
  'Waste Treatment',
  'Printing industry',
  'Power',
  'Telecommunications & Media',
  'Textile industry',
  'Hide & leather industry',
  'Automotive & Parts',
  'Transportation & Logistics',
  'Water Treatment',
  'Wood industry'
];

export const PRICING_SUB_CATEGORY = [
'Others',
'Theatre/ auditorium/ opera/ cinema',
'Casino : floating',
'Hotels/ motel/ vacation resort',
'Hospital/ nursing home/ medical day care center',
'Offices',
'Restaurants chain',
'Others (residential/ real estate …)',
'Other/ Unspecified commercial',
'Amusement park/ holidays activity center',
'Museum/ library',
'Prison or jail',
'Religious building',
'University/ school',
'Stadium/ arena',
'Cold storage',
'Stores/supermarket',
'Logistics (medium hazards)',
'Mall/ shopping center/ market hall',
'Other storage',
'Grain silo',
'High hazard eg ammonium nitrate',
'Explosives',
'Semiconductor testing/ assembly & packaging/ Display panel modules',
'Accumulators production',
'Household appliance industry',
'Electronic assembling (Mobile phones/ PC/ Notebook/ Disk drives…) with very limited CBI Exposure',
'Semiconductor/ Display panel fabs',
'3rd party electronic manufacturing and assembly - CBI represents most significant risk to insured',
'Bakery',
'Cigars & cigarettes production',
'Cocoa & coffee roasting',
'Dairy : milk powder',
'Dairy : other',
'Other food processing',
'Meat/ fish processing plant',
'Cereal mills',
'Alcohol-free bottling with plastic molding',
'Oil press (mechanical)',
'Oil extraction (chemical)',
'Slaughterhouse',
'Starch factory',
'Sugar refinery',
'Aircraft and Parts',
'Cable manufacturing',
'Heavy machinery production (pump/ compressor/ turbine)',
'Metal surface treatment',
'Non ferrous metal processing',
'Railway vehicle manufacturing',
'Guided Missiles/ Space Satellites & Vehicles',
'Ship and Boat Building',
'Alumina refinery',
'Aluminum smelter',
'Standard',
'Aggravated',
'Steel plant with blast furnace',
'Steel plant with direct reduction',
'Metal extruding',
'Gravel quarrying',
'Rolling mill',
'Others building materials',
'Tiles/ bricks or refractories factory',
'Plaster & cement production without rotary kiln',
'Cement production site with rotary kiln',
'Coated shingle factory',
'Concrete production',
'Glass manufacturing',
'Lime or gypsum products',
'Sandwich panel factory (glass/ rock…) non combustible',
'Sandwich panel factory (pur…) combustible',
'Pipeline System (including compressor/ pumping stations)',
'Land Rig/ Production facility/ Unspecified',
'Pure Pipeline',
'Compressor/ Pumping Station',
'River Crossing',
'Ammonia/ Methanol Plant',
'Storage Terminal',
'LNG Plant',
'LNG Terminal - Regasification',
'Formulation/ packaging/ tableting',
'API/ manufacturing - biological',
'R&D laboratories',
'API/ intermediates mfg - chemical',
'Extrusion/ injection molding plastic goods factory',
'Foam no polyurethane',
'Foam polyurethane',
'Rubber goods factory',
'Tyre factory',
'Cardboard factory',
'Chemical pulp mill with BLRB or sulphites',
'Integrated paper mill (pulping including BLRB and paper production)',
'Mechanical pulp mill',
'Paper mill without pulp production',
'Waste paper recycling',
'Combined',
'Solvent based',
'Water based',
'Wadding and toilet paper',
'Wind power',
'Thermal (All)',
'Combined cycle gas turbine power plant',
'Geothermal power plant',
'Transmission',
'Simple cycle gas turbine power plant',
'Solar power',
'Computer center',
'TV or radio transmitting',
'Telecom supply (T&D excluded)',
'Overhead t&d lines',
'Submarine underground cable',
'Unspecified/ others textile',
'Clothing industry',
'Non woven fabrics',
'Shoe-manufacturing',
'Tannery',
'Airports & hangars',
'Repair garages',
'Railways operating/ infrastructure',
'Car parks',
'Harbors/ piers/ wharves',
'Railways maintenance',
'Desalination plant non-generating',
'Water processing',
'Refuses/ recycling/ composting',
'Industrial refuses incineration',
'Waste water treatment plant',
'Water',
'Sawmill',
'Furniture',
'Other wood industry',
'Tunnel',
'Dam (without power station)',
'Road',
'Road network (including other infrastructure: tunnel/ bridge/ toll…)',
'Bridge',
'Canal',
'Railways rolling stock static',
'Buses and lorries operating',
];

export const OPERATIONAL_STATUS = [
  'In Operation',
  'Idle'
];


export const LOCATION_REFERENCE_DATA = new Map<string, any[]>(
    [
      [LOCATION_FIELD_CODES_ENUM.construction_code , CONSTRUCTION_CODE],
      [LOCATION_FIELD_CODES_ENUM.construction_scheme , CONSTRUCTION_SCHEME],
      [LOCATION_FIELD_CODES_ENUM.occupancy_code , OCCUPANCY_CODE],
      [LOCATION_FIELD_CODES_ENUM.occupancy_scheme , OCCUPANCY_SCHEME],
      [LOCATION_FIELD_CODES_ENUM.original_country , COUNTRY],
      [LOCATION_FIELD_CODES_ENUM.cleansed_country , COUNTRY],
      [LOCATION_FIELD_CODES_ENUM.final_country , COUNTRY],
      [LOCATION_FIELD_CODES_ENUM.original_state , STATE],
      [LOCATION_FIELD_CODES_ENUM.final_state , STATE],
      [LOCATION_FIELD_CODES_ENUM.cleansed_state , STATE],
      [LOCATION_FIELD_CODES_ENUM.accord_occupancy_code , OCCUPANCY_CODE],
      [LOCATION_FIELD_CODES_ENUM.accord_occupancy_class , ACCORD_OCCUPANCY_CLASS],
      [LOCATION_FIELD_CODES_ENUM.accord_occupancy_subclass , ACCORD_OCCUPANCY_SUB_CLASS],
      [LOCATION_FIELD_CODES_ENUM.accord_construction_class , CONSTRUCTION_CLASS],
      [LOCATION_FIELD_CODES_ENUM.accord_construction_code ,   CONSTRUCTION_CODE],
      [LOCATION_FIELD_CODES_ENUM.cleansed_iso2 , ISO_2],
      [LOCATION_FIELD_CODES_ENUM.cleansed_iso3 , ISO_3],
      [LOCATION_FIELD_CODES_ENUM.final_iso2 , ISO_2],
      [LOCATION_FIELD_CODES_ENUM.final_iso3 , ISO_3],
      [LOCATION_FIELD_CODES_ENUM.accuracy_level , ACCURACY_LEVEL],
      [LOCATION_FIELD_CODES_ENUM.geocoder , GEOCODER],
      [LOCATION_FIELD_CODES_ENUM.accuracy_validated , ACCURACY_VALIDATED],
      [LOCATION_FIELD_CODES_ENUM.bi_type , BI_TYPE],
      [LOCATION_FIELD_CODES_ENUM.for_interest , FOR_INTEREST],
      [LOCATION_FIELD_CODES_ENUM.tiv_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.tiv_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.other_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.other_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.pd_value_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.pd_value_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.bi_value_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.bi_value_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.mpl_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.earthquake_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.earthquake_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.windstorm_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.windstorm_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.flood_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.flood_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.terrorism_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.terrorism_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.strike_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.strike_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.machinery_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.machinery_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.cyber_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.cyber_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_limit_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_combined_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_combined_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_pd_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_pd_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_building_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_building_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_structure_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_structure_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_content_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_content_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_machinary_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_machinary_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_stock_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_stock_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.fire_bi_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.fire_bi_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.pricing_category , PRICING_CATEGORY],
      [LOCATION_FIELD_CODES_ENUM.pricing_sub_category , PRICING_SUB_CATEGORY],
      [LOCATION_FIELD_CODES_ENUM.operational_status , OPERATIONAL_STATUS],
      [LOCATION_FIELD_CODES_ENUM.location_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_earthquake_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_earthquake_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_windstorm_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_windstorm_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_flood_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_flood_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_terrorism_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_terrorism_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_machinary_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_machinary_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_strike_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_strike_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_cyber_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_cyber_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_fire_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.binders_fire_deductible_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.first_floor_height_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.certified_elevation_height_unit , UNIT],
      [LOCATION_FIELD_CODES_ENUM.policy_limit_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.policy_excess_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.site_currency , CURRENCY],
      [LOCATION_FIELD_CODES_ENUM.asset_quality , ASSET_QUALITY],
      [LOCATION_FIELD_CODES_ENUM.mb_quality , MB_QUALITY],
      [LOCATION_FIELD_CODES_ENUM.bi_mitigation , BI_MITIGATION],
    ]
  );

export const COLOMN_LISTS = [
  'construction_code',
'construction_scheme',
'occupancy_code',
'occupancy_scheme',
'original_country',
'cleansed_country',
'final_country',
'original_state',
'final_state',
'cleansed_state',
'accord_occupancy_code',
'accord_occupancy_class',
'accord_occupancy_subclass',
'accord_construction_class',
'accord_construction_code',
'cleansed_iso2',
'cleansed_iso3',
'final_iso2',
'final_iso3',
'accuracy_level',
'geocoder',
'accuracy_validated',
'bi_type',
'for_interest',
'tiv_currency',
'tiv_unit',
'building_currency',
'building_unit',
'stock_currency',
'stock_unit',
'machinery_currency',
'machinery_unit',
'other_structure_currency',
'other_structure_unit',
'content_currency',
'content_unit',
'pd_value_currency',
'pd_value_unit',
'bi_currency',
'bi_unit',
'bi_value_unit',
'mpl_currency',
'earthquake_limit_unit',
'earthquake_combined_unit',
'earthquake_combined_currency',
'earthquake_pd_unit',
'earthquake_pd_currency',
'earthquake_building_unit',
'earthquake_building_currency',
'earthquake_structure_unit',
'earthquake_structure_currency',
'earthquake_content_unit',
'earthquake_content_currency',
'earthquake_machinary_unit',
'earthquake_machinary_currency',
'earthquake_stock_unit',
'earthquake_stock_currency',
'earthquake_bi_unit',
'earthquake_bi_currency',
'windstorm_limit_unit',
'windstorm_combined_unit',
'windstorm_combined_currency',
'windstorm_pd_unit',
'windstorm_pd_currency',
'windstorm_building_unit',
'windstorm_building_currency',
'windstorm_structure_unit',
'windstorm_structure_currency',
'windstorm_content_unit',
'windstorm_content_currency',
'windstorm_machinary_unit',
'windstorm_machinary_currency',
'windstorm_stock_unit',
'windstorm_stock_currency',
'windstorm_bi_unit',
'windstorm_bi_currency',
'flood_limit_unit',
'flood_combined_unit',
'flood_combined_currency',
'flood_pd_unit',
'flood_pd_currency',
'flood_building_unit',
'flood_building_currency',
'flood_structure_unit',
'flood_structure_currency',
'flood_content_unit',
'flood_content_currency',
'flood_machinary_unit',
'flood_machinary_currency',
'flood_stock_unit',
'flood_stock_currency',
'flood_bi_unit',
'flood_bi_currency',
'terrorism_limit_unit',
'terrorism_combined_unit',
'terrorism_combined_currency',
'terrorism_pd_unit',
'terrorism_pd_currency',
'terrorism_building_unit',
'terrorism_building_currency',
'terrorism_structure_unit',
'terrorism_structure_currency',
'terrorism_content_unit',
'terrorism_content_currency',
'terrorism_machinary_unit',
'terrorism_machinary_currency',
'terrorism_stock_unit',
'terrorism_stock_currency',
'terrorism_bi_unit',
'terrorism_bi_currency',
'strike_limit_unit',
'strike_combined_unit',
'strike_combined_currency',
'strike_pd_unit',
'strike_pd_currency',
'strike_building_unit',
'strike_building_currency',
'strike_structure_unit',
'strike_structure_currency',
'strike_content_unit',
'strike_content_currency',
'strike_machinary_unit',
'strike_machinary_currency',
'strike_stock_unit',
'strike_stock_currency',
'strike_bi_unit',
'strike_bi_currency',
'machinery_limit_unit',
'machinery_combined_unit',
'machinery_combined_currency',
'machinery_pd_unit',
'machinery_pd_currency',
'machinery_building_unit',
'machinery_building_currency',
'machinery_structure_unit',
'machinery_structure_currency',
'machinery_content_unit',
'machinery_content_currency',
'machinery_machinary_unit',
'machinery_machinary_currency',
'machinery_stock_unit',
'machinery_stock_currency',
'machinery_bi_unit',
'machinery_bi_currency',
'cyber_limit_unit',
'cyber_combined_unit',
'cyber_combined_currency',
'cyber_pd_unit',
'cyber_pd_currency',
'cyber_building_unit',
'cyber_building_currency',
'cyber_structure_unit',
'cyber_structure_currency',
'cyber_content_unit',
'cyber_content_currency',
'cyber_machinary_unit',
'cyber_machinary_currency',
'cyber_stock_unit',
'cyber_stock_currency',
'cyber_bi_unit',
'cyber_bi_currency',
'fire_limit_unit',
'fire_combined_unit',
'fire_combined_currency',
'fire_pd_unit',
'fire_pd_currency',
'fire_building_unit',
'fire_building_currency',
'fire_structure_unit',
'fire_structure_currency',
'fire_content_unit',
'fire_content_currency',
'fire_machinary_unit',
'fire_machinary_currency',
'fire_stock_unit',
'fire_stock_currency',
'fire_bi_unit',
'fire_bi_currency',
'pricing_category',
'pricing_sub_category',
'operational_status',
'location_currency',
'binders_earthquake_limit_currency',
'binders_earthquake_deductible_currency',
'binders_windstorm_limit_currency',
'binders_windstorm_deductible_currency',
'binders_flood_limit_currency',
'binders_flood_deductible_currency',
'binders_terrorism_limit_currency',
'binders_terrorism_deductible_currency',
'binders_machinary_limit_currency',
'binders_machinary_deductible_currency',
'binders_strike_limit_currency',
'binders_strike_deductible_currency',
'binders_cyber_limit_currency',
'binders_cyber_deductible_currency',
'binders_fire_limit_currency',
'binders_fire_deductible_currency',
'first_floor_height_unit',
'certified_elevation_height_unit',
'policy_limit_currency',
'policy_excess_currency',
'site_currency',
'asset_quality',
'mb_quality',
'bi_mitigation',
];


